server:
  port: 8080
  servlet:
    context-path: /iam

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: tvtdeptrainvt@gmail.com
    password: knepeihehumbatzg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "H70wBs8w6tYCEItpxkMMcuZ924MoFhkv6sqPk9nnRybuwCo4SOI0vaE/3bzkBZ4e"
  valid-duration: 3600
  refreshable-duration: 36000

cloudinary:
  cloud-name: dvlpxoasr
  api-key: 854494321823681
  api-secret: _PZF0P2BDAWgO8Kqw5sFyq_ShNg