server:
  port: 8080
  servlet:
    context-path: /iam

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 771423921859-uo3vo9gq170hvpc3o77imks14i4k4pps.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - email
              - profile
            provider: google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: tvtdeptrainvt@gmail.com
    password: knepeihehumbatzg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "H70wBs8w6tYCEItpxkMMcuZ924MoFhkv6sqPk9nnRybuwCo4SOI0vaE/3bzkBZ4e"
  valid-duration: 3600        # 1h
  refreshable-duration: 36000 # 10h

cloudinary:
  cloud-name: dvlpxoasr
  api-key: 854494321823681
  api-secret: _PZF0P2BDAWgO8Kqw5sFyq_ShNg

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
